import './Privacy.css';

export default function Privacy () {

    return(
        <div className='termsMain'>
            <h1 className='termsHeader spaceBelow'>Privacy Policy</h1>
            <p className='spaceBelow'>Last Updated: December 20, 2023</p>
            <p className='spaceBelow'>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p className='spaceBelow'>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            <p className='spaceBelow'>Interpretation and Definitions</p>
            <p className='spaceBelow'>Interpretation</p>
            <p className='spaceBelow'>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <p className='spaceBelow'>Definitions</p>
            <p className='spaceBelow'>For the purposes of this Privacy Policy:</p>
            <p><span className='bolder'>Account </span>means a unique account created for You to access our Service or parts of our Service.</p>
            <p><span className='bolder'>Affiliate</span>means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
            <p><span className='bolder'>Company</span>(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to The creator of this site, Jordan Lopez</p>
            <p><span className='bolder'>Country</span> refers to California, USA</p>
            <p><span className='bolder'>Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
            <p className='spaceBelow'><span className='bolder'>Personal Data</span> is any information that relates to an identified or identifiable individual.</p>
            <p className='spaceBelow'><span className='bolder'>Service </span>refers to this website</p>
            <p className='spaceBelow'><span className='bolder'>Service Provider </span>means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
            <p className='spaceBelow'><span className='bolder'>Third Party Social Media Service</span>refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
            <p className='spaceBelow'><span className='bolder'>Usage Data </span>refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            <p className='spaceBelow'><span className='bolder'>You </span>means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            <p className='spaceBelow bolder'>Collecting and Using Your Personal Data</p>
            <p className='spaceBelow'>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <p className='spaceBelow'>Email Address <br></br> First Name and Last Name <br></br>Usage Data</p>
            <p className='spaceBelow'>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p className='spaceBelow'>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            <p className='spaceBelow'>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            <p className='spaceBelow bolder'>Information from Third-Party Social Media Services</p>
            <p className='spaceBelow'>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services: Google</p>
            <p className='spaceBelow'>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
            <p className='spaceBelow'>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
            <p className='spaceBelow bolder'>Tracking Technologies and Cookies</p>
            <p className='spaceBelow'>We do NOT use any tracking technologies or Cookies</p>
            <p className='spaceBelow bolder'>Retention of Your Personal Data</p>
            <p className='spaceBelow'>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p className='spaceBelow bolder'>Transfer of Your Personal Data</p>
            <p className='spaceBelow'>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
            <p className='spaceBelow'>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
            <p className='spaceBelow'>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
            <p className='spaceBelow bolder'>Business Transactions</p>
            <p className='spaceBelow'>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
            <p className='spaceBelow bolder'>Law enforcement</p>
            <p className='spaceBelow'>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            <p className='spaceBelow bolder'>Other legal requirements</p>
            <p className='spaceBelow'>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <p className='spaceBelow'>Comply with a legal obligation <br/>Protect and defend the rights or property of the Company <br />Prevent or investigate possible wrongdoing in connection with the Service <br />Protect the personal safety of Users of the Service or the public <br />Protect against legal liability</p>
            <p className='spaceBelow bolder'>Security of Your Personal Data</p>
            <p className='spaceBelow'>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            <p className='spaceBelow bolder'>Children's Privacy</p>
            <p className='spaceBelow'>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
            <p className='spaceBelow'>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
            <p className='spaceBelow bolder'>Links to Other Websites</p>
            <p className='spaceBelow'>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            <p className='spaceBelow'>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
            <p className='spaceBelow bolder'>Changes to this Privacy Policy</p>
            <p className='spaceBelow'>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
            <p className='spaceBelow'>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
            <p className='spaceBelow'>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            <p className='spaceBelow bolder'>Contact Us</p>
            <p className='spaceBelow'>If you have any questions about this Privacy Policy, You can contact us:</p>
            <p className='spaceBelow'>By email: univcaliforniaai@gmail.com</p>
            <p className='spaceBelow'></p>
            <p className='spaceBelow'></p>
            <p className='spaceBelow'></p>
            <p className='spaceBelow'></p>
            <p className='spaceBelow'></p>
        </div>
    );
}   